### PR TITLE
Enhanced the navbar

### PR DESCRIPTION
**Pull request by akshaykaluse35**
Changed the previous hover effect, coz it was not great for our theme..... Added smooth and nice hover effect to navbar

### CODE REVIEW

**Comment by maitri-vv** [comment]
@akshaykaluse35 your changes to the font style, made whole website's font style headings different from the theme set previously. and moreover i feel navbar fonts are already in style with theme. but you can definitely try to lookout the issues on login signup pages and work over it. as of now i am closing this issue, i hope you understand :)

**Comment by akshaykaluse35** [comment]
@maitri-vv 
Ummm, I'm sorry for that.... I can change the font to previous one, if you reopen this issue...
It'll be beneficial for me on the occasion of hacktoberfest. There are just 7 days left. And I'll also look for the issues on login/signup pages. Thank You

**Comment by maitri-vv** [comment]
okay i will reopen as you mentioned while opening the issue, you want to change the hover effect by transitioning it a bit smoother....go ahead with this... do not change the font style, works?

**Comment by akshaykaluse35** [comment]
@maitri-vv Thank You so much :)

**Comment by akshaykaluse35** [comment]
Do check the preview, If there is any other cnflct I'll make sure to change.... Thank You :)

**Comment by maitri-vv** [comment]
image
image

@akshaykaluse35 see this font is changing from high bold to just bold/ its normal weight. your changes to nav fonts made whole website's headings change to that thinner styled font. i do not find that enhancing user experience, hence i closed the prev changes but again now, the changes u made looked changing the same things :(

**Comment by akshaykaluse35** [comment]
ooops I'm sorry, I didn't noticed that 
Just gimme 5 min I'll resolve

**Comment by maitri-vv** [comment]
@akshaykaluse35 i would appreciate if you can work on another issue as the chnages to navbar is already enhanced properly. you can raise new issue and pr's i will accept that but i genuinely feel navbar does'nt need more attention. let me know if you have any doubts on discussion of this repository.

**Pull request closed without merging**
