### PR TITLE
First commit(Added animations and transition)etc..

### PR DESCRIPTION
**Pull request by Ananta2545**
changes made:-
1. Improved the visual experience.
2. Added some attractive transitions.
3. Added some animations.
4. Improved the navbar to some extent.
5. slightly improved the downloads buttons.
6. designed the menu items.

### CODE REVIEW

**Comment by maitri-vv** [comment]
hey @Ananta2545 , the code you submitted changes the theme of the website, we had consistency for all the sections of the website, if possible retain the text animation and add colours of the nav buttons according to theme.

**Comment by Ananta2545** [comment]
OK.

**Comment by yash19sinha** [comment]
Please try to resolve the conflicts first

**Comment by Ananta2545** [comment]
I have resolved the conflicts.

**Comment by maitri-vv** [comment]
image

image

image

image

image


@Ananta2545 your changes are breaking responsiveness. Please try to retain it. I really liked the animations and button you changed for UI but if I merge this code it will break entire page. Hence, I am closing this PR, but you can raise new issue and PR with better enhancement and consisteny, I hope you understand :)

**Comment by Ananta2545** [comment]
Will surely do.

**Pull request closed without merging**
