### PR TITLE
second commit(Hovering effect on download buttons and color animation etc).

### PR DESCRIPTION
**Pull request by Ananta2545**
Changed:- 
1.  Applied Color animation in heading 1.
2.  Applied hovering effect in buttons(downloads).
3. Create a typewriter type effect on the paragraph under heading.

This all changes are applied by maintaining the responsiveness and theme of the website.
 Demo Picture:-
image
image
image

Issue close:- #36 

Please merge my pull request under hacktoberfest 2023.

### CODE REVIEW

**Comment by maitri-vv** [comment]
GTG @Ananta2545 just resolve the merge conflicts, i will merge it :)

**Comment by Ananta2545** [comment]
I have resolved the conflicts. Thanks @maitri-vv

**Comment by maitri-vv** [comment]
@Ananta2545 now the UI has changed after conflicts :( you can preview it right?

**Comment by Ananta2545** [comment]
Sorry for the inconvenience. I have resolved the problem @maitri-vv. Please check.

**Comment by maitri-vv** [comment]
No worries. Thanks for contribution *_*

**Pull request merged**
