### PR TITLE
The-Improved navbar-function-and-better-UI-55

### PR DESCRIPTION
**Pull request by RonitBaranwal**
The navbar has been improved with all the  links working and the UI also made better with hover effect for all the nav-links and better size for the logo of the company which was a little bigger previouly.
If you want any other updates please let me know.

### CODE REVIEW

**Comment by RonitBaranwal** [comment]
But I guess The issue of functionalities of nav-links was already done by someone before.
So should I close this pr??

**Comment by yash19sinha** [comment]
Can you try to increase the logo size and title little bit

**Comment by RonitBaranwal** [comment]
Alright will do it .

**Comment by yash19sinha** [comment]
Can you share screenshots of the changes you have done

**Comment by RonitBaranwal** [comment]
Sorry was bit busy with my college work will do it .

**Pull request merged**
